[package]
name = "generate_reflection"
version = "0.1.0"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
edition = "2018"
publish = false

[dependencies]
bitflags = "1.0.4"
futures = "0.1"
heck = "0.3.1"
hyper = "0.12"
lazy_static = "1.3.0"
log = "0.4.6"
notify = "4.0.15"
proc-macro2 = "1.0.6"
quote = "1.0.2"
rbx_dom_weak = { path = "../rbx_dom_weak" }
rbx_xml = { path = "../rbx_xml" }
regex = "1.1.2"
roblox_install = "0.2.1"
serde = "1"
serde_derive = "1"
serde_json = "1"
snafu = "0.6.0"
tempfile = "3"
toml = "0.5.0"
