# Patches up basic properties of Instance.

[Change.Instance.className]
Kind = { Type = "Alias", AliasFor = "ClassName" }

[Change.Instance.Archivable]
Kind = { Type = "Canonical", Serialization = { Type = "SerializesAs", Name = "archivable" } }

[Change.Instance.archivable]
Kind = { Type = "Alias", AliasFor = "Archivable" }

# Tags serialize as a \0-delimited BinaryString of the tags on the instance.
[Add.Instance.Tags]
Kind = { Type = "Canonical", Serialization = { Type = "Serializes" } }
DataType = { Type = "Value", Name = "BinaryString" }
Scriptability = "Custom"