[package]
name = "rbx_types"
version = "0.1.0"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "0.1.3"
bitflags = "1.2.1"
lazy_static = "1.4.0"
rand = "0.7.3"
serde = { version = "1.0.104", features = ["derive"], optional = true }

[dev-dependencies]
bincode = "1.2.1"
serde_json = "1.0.45"

[features]
default = []
