[package]
name = "run_in_roblox"
version = "0.1.0"
authors = ["lgreathouse <me@lpghatguy.com>"]
edition = "2018"

[dependencies]
rouille = "3.0.0"
tempfile = "3.0.6"
rbx_dom_weak = { version = "0.3.0", path = "../rbx_dom_weak" }
rbx_xml = { version = "0.3.0", path = "../rbx_xml" }
