[package]
name = "rbx_binary"
description = "Weakly-typed Roblox DOM implementation for Rust"
license = "MIT"
documentation = "https://docs.rs/rbx_tree"
homepage = "https://github.com/LPGhatguy/rbx-tree"
repository = "https://github.com/LPGhatguy/rbx-tree.git"
version = "0.2.0"
authors = ["lgreathouse <me@lpghatguy.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2.7"
log = "0.4.6"
lz4 = "1.23.1"
rbx_tree = { version = "0.2.0", path = "../rbx_tree" }

[dev-dependencies]
env_logger = "0.6.0"
