[package]
name = "rbx_reflection_database"
version = "0.1.0"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rbx_reflection = { path = "../rbx_reflection" }

lazy_static = "1.4.0"
serde = "1.0.104"
rmp-serde = "0.14.2"
