[package]
name = "rbx_util"
version = "0.1.0"
description = "Utilities for working with Roblox model and place files"
license = "MIT"
documentation = "https://docs.rs/rbx_util"
homepage = "https://github.com/Roblox/rbx-dom"
repository = "https://github.com/Roblox/rbx-dom.git"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
edition = "2018"
readme = "README.md"

# This tool is not even close to ready for primetime!
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
path = "src/main.rs"
name = "rbx-util"

[dependencies]
anyhow = "1.0.31"
fs-err = "2.3.0"
rbx_binary = { path = "../rbx_binary", version = "0.6.0-dev", features = ["unstable_text_format"] }
rbx_xml = { path = "../rbx_xml", version = "0.12.0-dev" }
serde_yaml = "0.8.13"
structopt = "0.3.15"
