[package]
name = "rbx_xml"
description = "Weakly-typed Roblox DOM implementation for Rust"
license = "MIT"
documentation = "https://docs.rs/rbx_tree"
homepage = "https://github.com/LPGhatguy/rbx-tree"
repository = "https://github.com/LPGhatguy/rbx-tree.git"
version = "0.1.0"
authors = ["lgreathouse <me@lpghatguy.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
lazy_static = "1.2.0"
log = "0.4.6"
maplit = "1.0.1"
rbx_tree = { version = "0.1.0", path = "../rbx_tree" }
xml-rs = "0.8"
base64 = "0.10.0"

[dev-dependencies]
env_logger = "0.6.0"
