[package]
name = "rbx_xml"
description = "Weakly-typed Roblox DOM implementation for Rust"
version = "0.11.5"
license = "MIT"
documentation = "https://docs.rs/rbx_xml"
homepage = "https://github.com/rojo-rbx/rbx-dom"
repository = "https://github.com/rojo-rbx/rbx-dom.git"
readme = "README.md"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
edition = "2018"

[dependencies]
base64 = "0.11.0"
log = "0.4.6"
rbx_dom_weak = { version = "1.10.0", path = "../rbx_dom_weak" }
rbx_reflection = { version = "3.3.408", path = "../rbx_reflection" }
xml-rs = "0.8.0"

[dev-dependencies]
env_logger = "0.7.1"
insta = "0.12.0"
rbx_dom_test = { path = "../rbx_dom_test" }
