[package]
name = "rbx_reflection"
version = "0.1.0"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.2"
failure = "0.1.5"
rbx_dom_weak = { version = "0.2.0", path = "../rbx_dom_weak" }
